[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:hermes]
command=/home/hermes/.local/bin/hermes gateway
directory=/home/hermes
user=hermes
autostart=false
autorestart=true
environment=HOME="/home/hermes",PATH="/home/hermes/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",OPENAI_BASE_URL="https://openrouter.ai/api/v1",OPENAI_API_KEY="YOUR_OPENROUTER_SK_OR_KEY_HERE",HERMES_MODEL="deepseek/deepseek-v4-flash",HERMES_COMPRESSION_MODEL="openai/gpt-4.1-nano",HERMES_AUXILIARY_MODEL="openai/gpt-4.1-nano"
stderr_logfile=/var/log/supervisor/hermes.err.log
stdout_logfile=/var/log/supervisor/hermes.out.log
